sudo: false
language: node_js
branches:
  only:
  - master
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:\-[0-9]+)?$/
node_js:
- 4
- 6
cache:
  directories:
  - node_modules
  - $HOME/.npm
env:
  matrix:
  - CXX=g++-4.8
notifications:
  slack:
    secure: juLV1VV5GosvL9hEW5Sr0bqDgWnm24VfjhGVt8slad5ObdGoebCmheb4GdkBP+yArtnA0XeV+W76ROeVlmOaUSlgIXPuI3aiKBvDM7mCtfH5hHjngEknITN8jcSRh7lp4K5cDo8kHcFghy+F+VFD777HStPG20wFQ6m7CSWjvVq/0Me+hfZ8UvKZU8KKMaWsQwEqm3KdjlqDKSzdd/sP7FxhetPdQYYYl5YucFLfwB9TJfurFcu4fvS4UF3P3PcRe5hcnMh9nI7GHDXXDSpSsR5cSgMtFKzKa/HrwiBLUObEXYNk6Ui4g2AA9nJ5uFPDRK3u6bKriIW5PlYubLkwGmgSaQpHAaesLOgfnNoo/eHuvjc5L/IqLum7coC0F/gFgUuG+OVJ5wVWJY/EKEMSkdT8mMBAuK+Qd3yUdKcEoF7bZRveJwR1aPvHxLPqbzo64RKrdIA656Buh4PGZV2mBYRLEb95N+kQ2DgPqWzDxPhg5TxMi5OBGe2uQPJ+29u+x5tQzZCgFnbcs9W9Gg8PK65NfX1vQGh8T8KUCrYF8x2oG6uyplLxvp02ptinr+d4O49YL8GE9xyHbxuTKyeFGvoIY2kRG4kZIBjOKF86j7n/0qPOtOgMl1LvqtCMCgcsdOk1RI6JlB1LlkPzdEQvBgJ+amcqDxoRFdBKic74gdA=
deploy:
  provider: npm
  email: jeffandersen@gmail.com
  api_key:
    secure: x0PZEC3ktsfHqT9SmSskp70Ra1h0bvzBWJmq0phpIQtrnetthZ0nyM73GZgWmQ0HWZprs/fXkvkWQ2xjAqzN8LH3oIyIXkfFcighWb79R5cLJeKcYEUBnwejSEaDs1M2b5NiJWujejK9wHQZ/KCRTTpEV2hpa9keexvXXe8zkEzpFriUyYZ0+8FlZShXGhgjTCQh1OUM8Lt5pZB9xa9MSHYBpd1y1d9N/fF5rwaoD3ZY7CgYzwhs8skgQNXcdsRQ4IuJWe0x5BeZuFcjWM3Wwy6EzH42POuVHw2rQYNTT8kO5PNnUe4om40nWoRo4gfCapnJ3UOFFVbUPG4DucqcRoui+xz1lgR65UPm9bn58ETsKa4N2DmQjIg0KpzIHh8HwP3Op0HN+87lqxLvp/rFcLurY782XRDqO1B36cOVnnkWuDu7rle0+mGNt34Ij5a3cHdsQlPpeySnHGEnQOV7JegHJUozc9UWHqqrEHG8BYtUWfAyBCYZj+jBbCe8Alln/5HOh2IyB6IuqPnFq3HgLIKKju8jHM+3LYtC2ohv+TpOCUq+3lF7cW73FUkx7gj6xerefTrjurX6WGVZMZd6Xe+OQ+xUF0jM7AEJ79g9RuBBfDT8XKeacRETXL06deC5Wo+a2ONWeXp42sefbj+04FT554BsxPYU79I7pHHWNdE=
  on:
    tags: true
    repo: manifoldco/node-signature
