sudo: false
language: node_js
branches:
  only:
  - master
node_js:
- 4
- 6
cache:
  directories:
  - node_modules
  - $HOME/.npm
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack:
    secure: juLV1VV5GosvL9hEW5Sr0bqDgWnm24VfjhGVt8slad5ObdGoebCmheb4GdkBP+yArtnA0XeV+W76ROeVlmOaUSlgIXPuI3aiKBvDM7mCtfH5hHjngEknITN8jcSRh7lp4K5cDo8kHcFghy+F+VFD777HStPG20wFQ6m7CSWjvVq/0Me+hfZ8UvKZU8KKMaWsQwEqm3KdjlqDKSzdd/sP7FxhetPdQYYYl5YucFLfwB9TJfurFcu4fvS4UF3P3PcRe5hcnMh9nI7GHDXXDSpSsR5cSgMtFKzKa/HrwiBLUObEXYNk6Ui4g2AA9nJ5uFPDRK3u6bKriIW5PlYubLkwGmgSaQpHAaesLOgfnNoo/eHuvjc5L/IqLum7coC0F/gFgUuG+OVJ5wVWJY/EKEMSkdT8mMBAuK+Qd3yUdKcEoF7bZRveJwR1aPvHxLPqbzo64RKrdIA656Buh4PGZV2mBYRLEb95N+kQ2DgPqWzDxPhg5TxMi5OBGe2uQPJ+29u+x5tQzZCgFnbcs9W9Gg8PK65NfX1vQGh8T8KUCrYF8x2oG6uyplLxvp02ptinr+d4O49YL8GE9xyHbxuTKyeFGvoIY2kRG4kZIBjOKF86j7n/0qPOtOgMl1LvqtCMCgcsdOk1RI6JlB1LlkPzdEQvBgJ+amcqDxoRFdBKic74gdA=
deploy:
  provider: npm
  email:
    secure: Bn4P392rxNzaVv2MgXp83zZofaTKtSDr92pgsTJN2CD8/9QxmsivOpT7ADEJ7MZPJRZmh6Ivk6ed+P1doOvHcU1yTMQBN+NOUEA3HeUuYaN7/iElMTE3DVgn6TXNWQcJGFyYjCT8aqgs2Lve/t1Dy0aLLdpIaZ4q1RSnXua5qYQ3ZhvsYAo7uAhDGGPUyY6NPGzr5nyssAH6393qNS13dDyyTkTweS/RbFh4Llo74Fh6aCUfDaguuRgT4CdYkZ8VjNR/ZYam7fa5pd9ULNJ+Ml9WeKqlx8P5hRbo5BwTg+xsAtqGlZy1UDjNjeTB1fppijHGk+6PTKC7RzaPV1cIPwrWIzyTlno978lAsvoVVMbyiGc8nOfxOv+HTdxCdH7qVMtvzQJmJMvzV4l+0Hw9oQuL8jRanakCcywb+e0igou4xzIiv/oJ+dcJ/nGPam2HNG2x6B8+fGes4iK6K0Nw8NuJzBgTpX4VPa8qtc5oTHnZKfFZyu32SFlP9W0dJzliQ6yYr6ZJVjFdh3i9HzbBRzoxBjkFX7uzU4FSJ3+W8Gp4vKhWpdKWazLl5pzw7EOr0rkdXM4FqXOxMo0vwkLuocj80VQ2iVlPaRs/X9gSUUDYMPc2nQ+wIpC3xnt/vuhbaHH23fLxwrDpk7L/mTDeg5GPZvo/hmuUi8xftXYfhmU=
  api_key:
    secure: WC/iPKo4f8UiPxWa79HXZKAfFCZOAeWzkrrF2z/QoshWYqmZXOqnoYtFPezsfNn2fGJ7W6suo/QOFTalFevi97jSX11lIgNcmrAVPHDJBRWY3ZOykQ69xkvoy+1XiOUXHVxfTY8vhbN++4G1AP+GK2hoVe+BO+XYZV49+SW4yFIKIJHN1GhCbAKNlUOcw0yfnaOrBe98fEJtdXW1cRzEpzslRfgUxyA45818dtIGqOxwvNPqLioGSFXs9t2gV3c6dp0te0ggVF24t7G5CoWBwuUwIsZPZC5Xevgv8SZSiY2ILLpIeL9SWo8wLHSZBBXMF6tZSl5XfHncOcQOzrtCf09oOsk1HD6SdupYor51KjqhFQSKGilBu1WNsN0pNn9R9yT86uTFbNBV8xi0wjBgc7wlYNfWpEoQ+G5wwDxysEgTpmkOKDvEp0B7ROCbBzxXeDwiJTJR0KTYQ+AYCZ4ndrZjKLHYrQG4E997yLXfMdA4J+2qpyv6CBsxwmVfiEv2cwubX6a5rpFipzcIhdYJqix9FwmtOLPCfTinap2i12+Np4uowXlymdU9yc60GHorjJy5AZTc1IYhDNTaKF/xYSG4sl76w9qc+fimppVwdGhncC3e41O7KQ8k9jG6GaPvsvrKiEaJELAjLtkKwi1KO4veEfCTFdxjf46JmQRIIU0=
  on:
    tags: true
    condition: $TRAVIS_BRANCH =~ '^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:\-[0-9]+)?$'
    repo: manifoldco/node-signature
