sudo: false
language: node_js
branches:
  only:
  - master
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:\-[0-9]+)?$/
node_js:
- 4
- 6
cache:
  directories:
  - node_modules
  - $HOME/.npm
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: szmr4bX0Xk9A78CqjXXyZYnAMLgkFf/aWmVWDvXNJKaO8Hd9OmPUwPKosOY/PyLqhZhJBJlZHHGsZk9DPk9m0d9jXKuSKlnmL5/ussAMnx62nuK4dFsfpN0xUUIUc/WrI+GU1Xi/D+6M5A8Bp33wsBhABGnnkQSdU5GzX3aHYtEW4lMZX+xzmjff1imdUy73h4+8QKpaeFOrEwAQby83JMUD/6qUxTkDPygr3viGt4An6EuSbAWicMANlpl9469P0zIzFrg5ohqv7HjCYb+dseSMDkcs1fg4qua0jMC8UICEfDxz8tUMVHBpLzWIwME8iOh0mi2HFP65sUn54WZHbKhFsc2VN22cwtwPEYKLjrZVhxRaWGrroU2rwATIgKG0e1vnFF4X34f/S2SrjDlpRZ2C1wXzs7jH+++v+GqpqRdVgVP4y2yq/h6jZsT+kneMQQmYRiAOeqveW7yFYWuJCe492fUOrGRKBqk4FXer0YF4FeeyIlHTpxZYcIczxRWfd7m2SGpbMKNAExZM63/NMZ16Vfkev9q2bRQ1ctlo7XLSDh0g9B8NA8FJkbz021+u3Cg8mqPRYynpgIqcoAjZTw0Q+YKaz6FX2snVZDCtOP8RZ7IDT1l94fSh7Bmo8TTxcbdtzfK2VS1RvH8kmuh3QBiEE2f3ZnjtZleh48ilbw4=
notifications:
  slack:
    secure: juLV1VV5GosvL9hEW5Sr0bqDgWnm24VfjhGVt8slad5ObdGoebCmheb4GdkBP+yArtnA0XeV+W76ROeVlmOaUSlgIXPuI3aiKBvDM7mCtfH5hHjngEknITN8jcSRh7lp4K5cDo8kHcFghy+F+VFD777HStPG20wFQ6m7CSWjvVq/0Me+hfZ8UvKZU8KKMaWsQwEqm3KdjlqDKSzdd/sP7FxhetPdQYYYl5YucFLfwB9TJfurFcu4fvS4UF3P3PcRe5hcnMh9nI7GHDXXDSpSsR5cSgMtFKzKa/HrwiBLUObEXYNk6Ui4g2AA9nJ5uFPDRK3u6bKriIW5PlYubLkwGmgSaQpHAaesLOgfnNoo/eHuvjc5L/IqLum7coC0F/gFgUuG+OVJ5wVWJY/EKEMSkdT8mMBAuK+Qd3yUdKcEoF7bZRveJwR1aPvHxLPqbzo64RKrdIA656Buh4PGZV2mBYRLEb95N+kQ2DgPqWzDxPhg5TxMi5OBGe2uQPJ+29u+x5tQzZCgFnbcs9W9Gg8PK65NfX1vQGh8T8KUCrYF8x2oG6uyplLxvp02ptinr+d4O49YL8GE9xyHbxuTKyeFGvoIY2kRG4kZIBjOKF86j7n/0qPOtOgMl1LvqtCMCgcsdOk1RI6JlB1LlkPzdEQvBgJ+amcqDxoRFdBKic74gdA=
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: T/VDlw+Vhlda9zjgvdbkvPPEoIMlzisYT3mqKjGG7PP17wi8FLAWI84IGZnRErrW1aaXyOzCneN9DIICK2/mHpG90G+EsIMRShst/Wl8jUUgeuptOGEwEczrlg6miXHZzythRtruvfdSclLw6tNVCPTfmeXxPLMSY+iJyPaDP+ds7/InoUS+7eyknNIJvxVPLKnG6+3kfqKENrNqtwYdxTJaCXZkQhZlD2+psUSnlWGFexz3bn+dG9U9Z2a0TXgry2+4Zth3aa9JZnZI86Ag7eoxedagRIggVRkWLp2gZZPTC/wGcKbPXqWeYoprgaag/H1pOJ6C5cVTlydS9KEp35yW4cyRvlALWaEAPYl3H7cUw13vLUnqOgB8eEqoBwVkkCKVGvJf4JbRvq+oRZ2YeS1DnOc5PfjU4wTMgb6C+R0SlsehTlY4bqHDsNYVveK30GsjcjAi8SJnaiNGOl83FftTh1/2nNdjFzaVad48Sw1i1dh9UAAxVeUTPgGGq3DDZM/SV7xAzHDx0p6qNM/k9ataHWT0or5QBwOzgmvMViCkX81zFYIoC1QrGG6PUYLQF9J5LfV6ujyxCSZZWupj33VhYweZxYHgUCCl3ThrdGAQVLS1EWskRxhOxMOmiz6bkPR532IHhy1FWPShifaWQt0jvv2+iOtoD8P+fApqeRQ=
  on:
    tags: true
    repo: manifoldco/node-signature
